import { Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/generals/header/Header";
import { ThemeProvider } from "@/helpers/ThemeProvider";
import SmoothScrolling from "@/helpers/SmoothScrolling";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "2D Animator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${montserrat.className} ${roboto.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <SmoothScrolling />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
